apiVersion: v1
kind: Secret
metadata:
  name: {{ include "pi-dev-ops-backend.name" . }}-secret
  labels:
    {{- include "pi-dev-ops-backend.labels" . | nindent 4 }}
type: Opaque
data:
  jwtSecret: {{ .Values.app.jwtSecret | b64enc }}
  dbUser: {{ .Values.app.db.user | b64enc }}
  dbPassword: {{ .Values.app.db.password | b64enc }}